parameters:
  - name: AzureSubscription
    type: string
  - name: AcrName
    type: string
  - name: Repository
    type: string
  - name: DockerFile
    type: string
  
jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    steps:
      - template: steps-build-push-docker.yml@CI_CD
        parameters:
          azureSubscription: ${{parameters.AzureSubscription}}
          acrName: ${{parameters.AcrName}}
          repository: ${{parameters.Repository}}
          dockerFile: ${{parameters.DockerFile}}
